global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'raft-cluster'
    static_configs:
      # Node 0
      - targets: ['kv-0.kv-raft:8001']
        labels:
          pod: 'kv-0'  # Explicitly set the label for Grafana

      # Node 1
      - targets: ['kv-1.kv-raft:8001']
        labels:
          pod: 'kv-1'

      # Node 2
      - targets: ['kv-2.kv-raft:8001']
        labels:
          pod: 'kv-2'